import { IconProps } from ".";

export const DashboardIcon = ({ className }: IconProps) => (
  <svg
    viewBox="0 0 24 24"
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink"
    fill="currentColor"
    className={className}
  >
    <g strokeWidth={0} />
    <g
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <g>
      <title>{"Dashboard"}</title>
      <g
        id="Dashboard"
        stroke="none"
        strokeWidth={1}
        fill="none"
        fillRule="evenodd"
      >
        <rect
          id="Container"
          x={0}
          y={0}
          width={24}
          height={24}
        />
        <rect
          id="shape-1"
          stroke="currentColor"
          strokeWidth={2}
          strokeLinecap="round"
          x={4}
          y={4}
          width={16}
          height={16}
          rx={2}
        />
        <line
          x1={4}
          y1={9}
          x2={20}
          y2={9}
          id="shape-2"
          stroke="currentColor"
          strokeWidth={2}
          strokeLinecap="round"
        />
        <line
          x1={9}
          y1={10}
          x2={9}
          y2={20}
          id="shape-3"
          stroke="currentColor"
          strokeWidth={2}
          strokeLinecap="round"
        />
      </g>
    </g>
  </svg>
);